version: '3.4'
services:
  identityserver:
    build:
      context: .
      dockerfile: ./Dockerfile-IdentityServer
    ports:
      - 49504:8080
    container_name: crowe_identityserver

  webapi:
    build:
      context: .
      dockerfile: ./Dockerfile-WebApi
    ports:
      - 7228:8080
    container_name: crowe_webapi